In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style="ticks")

In [ ]:
data = pd.read_excel('toys.xlsx')

In [ ]:
data.shape

(150000, 6)

In [ ]:
data.shape

(150000, 6)

In [ ]:
data.isnull().sum()

Number     0
City       0
Gender     0
Age        0
Income     0
Illness    0
dtype: int64

In [ ]:
data.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

In [ ]:
total_count = data.shape[0]
print('Всего строк: {}'.format(total_count))

Всего строк: 150000

In [ ]:
data_new_3 = data.fillna(0)
data_new_3.head()

   Number    City Gender  Age  Income Illness
0       1  Dallas   Male   41   40367      No
1       2  Dallas   Male   54   45084      No
2       3  Dallas   Male   42   52483      No
3       4  Dallas   Male   40   40941      No
4       5  Dallas   Male   46   50289      No

In [ ]:
num_cols = []
for col in data.columns:
    # Количество пустых значений
    temp_null_count = data[data[col].isnull()].shape[0]
    dt = str(data[col].dtype)
    if temp_null_count>0 and (dt=='float64' or dt=='int64'):
        num_cols.append(col)
        temp_perc = round((temp_null_count / total_count) * 100.0, 2)
        print('Колонка {}. Тип данных {}. Количество пустых значений {}, {}%.'.format(col, dt, temp_null_count, temp_perc))

In [ ]:
data_num = data[num_cols]
data_num

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[150000 rows x 0 columns]

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator

In [ ]:
data_num_sis = data_num[['Age']]
data_num_sis.head()

KeyError: "None of [Index(['Age'], dtype='object')] are in the [columns]"

In [ ]:
indicator = MissingIndicator()
mask_missing_values_only = indicator.fit_transform(data_num_sis)
mask_missing_values_only

In [ ]:
cat_cols = []
for col in data.columns:
    # Количество пустых значений
    temp_null_count = data[data[col].isnull()].shape[0]
    dt = str(data[col].dtype)
    if temp_null_count>0 and (dt=='object'):
        cat_cols.append(col)
        temp_perc = round((temp_null_count / total_count) * 100.0, 2)
        print('Колонка {}. Тип данных {}. Количество пустых значений {}, {}%.'.format(col, dt, temp_null_count, temp_perc))

In [ ]:
cat_temp_data = data[['Age']]
cat_temp_data.head()